version: '3.1'

services:
  db:
    extends:
      file: common-services.yml
      service: db
    networks:
      - stocks-app-network
  app:
    container_name: stock-api
    image: mithwick93/stock-api
    build:
      context: ../
      dockerfile: ./infrastructure/Dockerfile
    networks:
      - stocks-app-network
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_URL: jdbc:postgresql://db:5432/stock-db

volumes:
  postgres-data:

networks:
  stocks-app-network: